### PR TITLE
Issue #60 - `off` with function doesn't work

### PR DESCRIPTION
**Pull request by cheplv**
Usage:
var eventType = "message";
var eventTypeFn = $sails.on(eventType);
$scope.$on('$destroy', function() {
......
$sails.off(eventType, eventTypeFn);
.....
});

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
The usage would require a function be passed as the second argument, but that is just missing from the comment and the PR looks fine. One thing I would note is that typically you would pass the original function as the second argument to `off`, and not what `on` returned. If you have to use what `on` returned, I'd say it should be more like angular's `$watch` and what `on` returned would be a function,  which when called removes the listener.

**Comment by TheSharpieOne** [comment]
Can you add some tests for this? (`on` a `function/spy`, expect it to be there (trigger the event, make sure the spy is called). `off` the thing that was `on`ed, expect it to not be there (trigger the event, make sure the spy is not called))

**Comment by cheplv** [comment]
Sorry - in description was missed callback i.e. usage will be as example:
function eventMessageHandler(msg) { .... }
var eventType = "message";
var eventTypeFn = $sails.on(eventType, eventMessageHandler);

**Comment by cheplv** [comment]
$sails.off must be called directly. Hope this will solve issue

**Pull request merged**
