### PR TITLE
Made npm package publishable

### PR DESCRIPTION
**Pull request by apinnecke**
Hey, please merge and publish to npm registry. Would like to use the package as an npm dependency!

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Would you care to also implement the angular import pattern http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support which will allow people to more simply `require('angular-sails')` when installing from npm

**Comment by apinnecke** [comment]
Yep @TheSharpieOne, I'm on it, thanks for that hint.

Luckily that would have been the next issue to be faced with, cause I'm working with browserify. ;)

**Comment by TheSharpieOne** [comment]
Just need the index.js to be added and for it to require angularjs and the non-minified dist file (`./dist/angular-sails.js`)

**Comment by apinnecke** [comment]
Yep @TheSharpieOne , that was it. Should be ready now. :)

**Pull request merged**
