### PR TITLE
Refactoring, Tests, and More

### LINKED ISSUE #34: Cross domain Standalone app issues
I set up duplicate Sails servers.  $sails works fine when Angular app is served from 1337.
Then specifying a sockets server in app.config():
```javascript
$sailsProvider.url = 'http://localhost:1338';
```
on 1338 gives
```
verbose: A socket.io client (PQjE7nvxWrwUrMDc50Dg) connected successfully!
```
but socket data is still comes from 1337
```
verbose: websocket writing 6:::1+[{"body":{"data":[{"user":{"username":"abc","email":"abc@123...
```
even when I put the full url in the get()
```javascript
$sails.get( 'http://localhost:1338' + url, function (models) {
```
and turn off session auth on 1338
```javascript
module.exports.policies = {
   'myController': true
}
```
Thanks,

### PR DESCRIPTION
**Pull request by TheSharpieOne**
This PR contains changes from the other two PRs, merged into one along with tests for everything that I thought needed tests.  This is a major change, but contains tests to ensure confidence in the changes.  I suggest that this be made into a major release version.

@psi-4ward Please help review this as it has your changes in it; pulled directly from your refactor-psi branch (used in #46)

This resolves #34, #45, #5, #42 and closes #46 and #43

### CODE REVIEW

**Comment by TheSharpieOne** [comment]
Whoops, looks like I forgot to write tests against the interceptors that were added.  I'll do that a little bit later, but this PR is good to go.

**Comment by TheSharpieOne** [comment]
Chai updated to v2 a few days and packages that use chai cannot agree on a version when doing a fresh npm install....

**Comment by TheSharpieOne** [comment]
Its a little funny when the tests work on my master and not this one.  The only thing I can think of is the way its tests the 'source' files.  It may actually load them in the wrong order?  So this now test the generated build file (which is what would be distributed).

**Comment by JetFault** [comment]
It would be nice to have a way to manually connect/disconnect: https://github.com/JetFault/angular-sails/blob/master/src/service/angular-sails.js#L114

**Comment by TheSharpieOne** [comment]
@JetFault `$sails.disconnect()` is already a function exposed through sails.io.js, it will disconnect the socket that is used by angular-sails.  But currently there is no way to start a new socket connection.  I'll look into adding a clean way, probably similar to what you did.

**Pull request merged**
